#!/bin/bash
# TOR external IP
if [ $BLOCK_BUTTON = 1 ]; then
    pidof tor | xargs sudo kill -HUP
fi

ip=$(curl --silent --socks5 localhost:9050 ifconfig.co)
country=$(curl --silent --socks5 localhost:9050 ifconfig.co/x-ifconfig-country)
printf " %s (%s)\n" $ip "$country"
